### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by kimxogus** [scalacenter/scoop-bloop#6] opened 2020-05-18 06:39 UTC
`scoop install bloop` fails with following error

```plain
PS C:\Users\kimxogus> scoop install bloop
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'bloop' (1.4.1) [64bit]
Starting download with aria2 ...
Download: [#c975db 0B/0B CN:1 DL:0B]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: c975db|OK  |    34KiB/s|C:/Users/kimxogus/scoop/cache/bloop#1.4.1#https_github.com_scalacenter_bloop_releases_download_v1.4.1_bloop-coursier.json
Download: Status Legend:
Download: (OK):download completed.
Checking hash of bloop-coursier.json ... ok.
Running installer script...
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading C:\Users\kimxogus\scoop\apps\bloop\1.4.1:latest.release
  not found: C:\Users\kimxogus\.ivy2\local\C\Users\kimxogus\scoop\apps\bloop\1.4.1
  not found: https://repo1.maven.org/maven2/C/\Users\kimxogus\scoop\apps\bloop\1.4.1/maven-metadata.xml
        at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:325)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:273)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at coursier.Resolve$.validate(Resolve.scala:323)
        at coursier.Resolve.validate0$1(Resolve.scala:112)
        at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:156)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Linking ~\scoop\apps\bloop\current => ~\scoop\apps\bloop\1.4.1
Creating shim for 'bloop'.
Can't shim 'bloop': File doesn't exist.
```

**Comment by jvican** [comment] 2020-05-18 08:12
Thanks for reporting, this is a dupe of https://github.com/scalacenter/bloop/issues/1281

**Closed as completed** 2020-05-18 08:12 UTC
